#公共配置
spring:
  #热部署
  devtools:
    restart:
      enabled: true
#      additional-paths: src/main/java
      exclude: /**
  #激活哪一个环境的配置文件
  profiles:
    active: dev
  #视图配置
  mvc:
    static-path-pattern: /static/**
  resources:
    static-locations: classpath:/static/
  #网络请求配置
  http:
      encoding:
        force: true
        charset: UTF-8
        enabled: true
  #模板引擎配置
  freemarker:
      #模板加载路径
      template-loader-path: classpath:/templates
      check-template-location: true
      prefer-file-system-access: false
      settings:
        template_update_delay: 0
        classic_compatible: true
        number_format: 0.######
        template_exception_handler: ignore
      request-context-attribute: request
      charset: UTF-8
      suffix: .ftl
      content-type: text/html


  #连接池配置
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    druid:
      validationQuery: SELECT 1
      initialSize: 10
      minIdle: 10
      maxActive: 200
      minEvictableIdleTimeMillis: 180000
      testOnBorrow: false
      testWhileIdle: true
      removeAbandoned: true
      removeAbandonedTimeout: 1800
      logAbandoned: true
      poolPreparedStatements: true
      maxOpenPreparedStatements: 100
  #缓存配置
  cache:
      type: ehcache
      cache-names: ssoserver
#mybatisPlus
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  #实体扫描，多个package用逗号或者分号隔离
  type-aliases-package: com.zhangcq.app.entity
  #executo执行器
  #executor-type: batch
  global-config:
    db-config:
      db-type: mysql
      #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
      id-type: id_worker_str
      #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
      field-strategy: not_null
      #驼峰下划线转换
      db-column-underline: true
      #刷新mapper 调试神器
      refresh-mapper: true
      #数据库大写下划线转换
      #capital-mode: true
      #序列接口实现类配置
      #key-generator: com.baomidou.springboot.xxx
      #逻辑删除配置
      #    logic-delete-value: 1
      #    logic-not-delete-value: 0
      #自定义填充策略接口实现
      meta-object-handler: com.zhangcq.app.common.base.AutofillMetaObjectHandler
      #自定义SQL注入器
      #sql-injector: com.baomidou.springboot.xxx
  configuration:
    #配置返回数据库(column下划线命名&&返回java实体是驼峰命名)，自动匹配无需as（没开启这个，SQL需要写as： select user_id as userId）
    map-underscore-to-camel-case: true
    cache-enabled: false
    #配置JdbcTypeForNull, oracle数据库必须配置
    jdbc-type-for-null: 'null'
    default-statement-timeout: 10000
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

---
#开发环境配置
server:
  #端口
  port: 8080
  tomcat:
        uri-encoding: UTF-8
        max-threads: 800
  servlet:
    session:
      timeout: 43200
spring:
  profiles: dev
  # 数据源配置
  datasource:
    url: jdbc:mysql://localhost:3306/bugs?useUnicode=true&characterEncoding=utf8&useSSL=false&tinyInt1isBit=true&allowMultiQueries=true
    username: root
    password: root
swagger:
  enable: true
#日志
logging:
  config: classpath:logs/logback.xml
  path: D:\logs\zqzc
#自定义配置内容
#项目日志开关
web:
  log:
    switch: false

#SSO认证中心核心配置
sso:
  tgtname: TGTNAME
  stname: STNAME
  loginUrl: http://www.zhangcq.com:8080/sso/login
  function: FUNCTION


---
#生产环境配置
server:
  #端口
  port: 2080
  tomcat:
        uri-encoding: UTF-8
        max-threads: 800
  servlet:
    session:
      timeout: 43200
spring:
  profiles: pro
  #redis配置
  # 数据源配置
  datasource:
    url: jdbc:mysql://rm-2ze484679jdc773fzuo.mysql.rds.aliyuncs.com:3306/usercenter?useUnicode=true&characterEncoding=utf8&useSSL=false&tinyInt1isBit=true&allowMultiQueries=true
    username: root
    password: NCBDchinayouthedu@)!*0912
swagger:
  enable: false
#日志
logging:
  config: classpath:logs/logback.xml
  path: /opt/zqzc/project/ssoserver/logs

#自定义配置内容
#项目日志开关
web:
  log:
    switch: true
#SSO认证中心核心配置
sso:
  tgtname: TGTNAME
  stname: STNAME
  loginUrl: http://sso.chinayouthedu.com:2080/sso/login
  function: FUNCTION

#综合评价对接配置
third:
  #是否启用第三方接口
  enable: false
  zhpj:
    interface: http://xxx/accessValidityCheck
#登录页所属品牌，默认home，格学教育：gexue
login:
  page:
    path: home
#    path: gexue








